addEventHandler('onPlayerJoin', root, function()
    fadeCamera(source, true, 5)
    spawnPlayer(source, 0, 0, 5)
    setCameraTarget(source, source)
    setCameraMatrix(source,  1057.2451171875, -1168.9931640625, 43.30207824707, 1468.388671875, -918.42474365234, 99.881813049316)
    setPlayerHudComponentVisible(source,'radar', false)
    setPlayerHudComponentVisible(source, "weapon", false)
    setPlayerHudComponentVisible(source, "ammo", false)
    setPlayerHudComponentVisible(source, "vehicle_name", false)
    setPlayerHudComponentVisible(source, "money", false)
    setPlayerHudComponentVisible(source, "clock", false)
    setPlayerHudComponentVisible(source, "health", false)
    setPlayerHudComponentVisible(source, "armour", false)
    setPlayerHudComponentVisible(source, "breath", false)
    setPlayerHudComponentVisible(source, "area_name", false)
    setPlayerHudComponentVisible(source, "crosshair", true)
    setElementData(source, 'panel', true)
    triggerEvent('call:ServerMusic', source, source)
    showChat(source, false)
end)